# Use the official PostgreSQL image as base
FROM postgres:13-alpine

# Set environment variables for the PostgreSQL database
ENV POSTGRES_USER=admin
ENV POSTGRES_PASSWORD=adminpassword
ENV POSTGRES_DB=receipts

# Expose the default PostgreSQL port
EXPOSE 5432

